### ISSUE TITLE
The seImpl(path.expand(input), verbose, fromFile) issue has been fixed

### ISSUE THREAD

**Issue by yihui** [ellocke/GithubPage#1]
FYI the `blogdown::serve_site()` problem you mentioned in your excellent blog post https://ellocke.github.io/post/r-troubleshooting-blogdown-hugo-for-windows-dummies/ should be fixed in blogdown v0.7 (which I just published to CRAN): https://github.com/rstudio/blogdown/releases/tag/v0.7 Thanks!

**Comment by ellocke** [comment]
Thanks for the shout-out! I finally edited the post.
